name: Deploy to Azure Function Slot

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Export requirements.txt (Poetry)
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self add poetry-plugin-export
          poetry export --format requirements.txt --output requirements.txt --without-hashes

      - name: Install dependencies
        run: |
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Deploy to slot via publish profile
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          slot-name: standby
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_SLOT }}
          respect-funcignore: true